doctrine:
  dbal:
    connections:
      toolforge_s1:
        host: "%env(REPLICAS_HOST_S1)%"
        port: "%env(REPLICAS_PORT_S1)%"
        user: "%env(REPLICAS_USERNAME)%"
        password: "%env(REPLICAS_PASSWORD)%"
      toolforge_s2:
        host: "%env(REPLICAS_HOST_S2)%"
        port: "%env(REPLICAS_PORT_S2)%"
        user: "%env(REPLICAS_USERNAME)%"
        password: "%env(REPLICAS_PASSWORD)%"
      toolforge_s3:
        host: "%env(REPLICAS_HOST_S3)%"
        port: "%env(REPLICAS_PORT_S3)%"
        user: "%env(REPLICAS_USERNAME)%"
        password: "%env(REPLICAS_PASSWORD)%"
      toolforge_s4:
        host: "%env(REPLICAS_HOST_S4)%"
        port: "%env(REPLICAS_PORT_S4)%"
        user: "%env(REPLICAS_USERNAME)%"
        password: "%env(REPLICAS_PASSWORD)%"
      toolforge_s5:
        host: "%env(REPLICAS_HOST_S5)%"
        port: "%env(REPLICAS_PORT_S5)%"
        user: "%env(REPLICAS_USERNAME)%"
        password: "%env(REPLICAS_PASSWORD)%"
      toolforge_s6:
        host: "%env(REPLICAS_HOST_S6)%"
        port: "%env(REPLICAS_PORT_S6)%"
        user: "%env(REPLICAS_USERNAME)%"
        password: "%env(REPLICAS_PASSWORD)%"
      toolforge_s7:
        host: "%env(REPLICAS_HOST_S7)%"
        port: "%env(REPLICAS_PORT_S7)%"
        user: "%env(REPLICAS_USERNAME)%"
        password: "%env(REPLICAS_PASSWORD)%"
      toolforge_s8:
        host: "%env(REPLICAS_HOST_S8)%"
        port: "%env(REPLICAS_PORT_S8)%"
        user: "%env(REPLICAS_USERNAME)%"
        password: "%env(REPLICAS_PASSWORD)%"
